testing fail on purpose

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,5 +17,9 @@ jobs:
         run: |
           echo ${{ inputs.text }}
           echo ${{ inputs.env }}
+      - name: Fail On Purpose
+        run: |
+          echo "I want to fail on purpose man!"
+          exit 1
     
       
